<div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                              
                                


                                <div class="card">
                                    <div class="card-header">
                                        <center>
                                        <strong>Registro y listado De Materias</strong>
                                    </center>

                                          
                        
                    
                        <button class="btn btn-info float-right" data-toggle="modal" data-target="#agregarmateria">
                        <span class="fa fa-plus"></span>
                Agregar nuevo 
				
			</button>


                                    </div>
 <div class="card-body card-block">

 <table id="table" class="display">
<thead>

<tr>
<th>Id</th>
<th>Nombre Materia</th>
<th>Grupo</th>
<th>Accion</th>
</tr>


</thead>

<tbody>

<?= $this->tabla ?>


</tbody>


</table>                                   
                                   

                                    
</div>


                                    




                                    <div class="card-footer">
                                        <center>
                                        <button type="submit" class="btn btn-primary btn-sm">
                                           Registrar Materia
                                        </button>
                                    </center>
                                    </div>
                                </div>










                            </div>
                            
                        </div>

                        </div>




 <!-- Modal para insertar los datos-->



<!-- Modal -->
<div class="modal fade" id="agregarmateria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Materia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" id="agregarMat">
      <div class="modal-body">
        
      <label>Nombre Materia</label>
<input type="text" id="nm" placeholder="Nombre de la materia" class="form-control">

        
      <label>Grupo</label>
    <select class="form-control" id="grup">
    <?= $this->grupos ?>  
    </select>
   


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">
        <span class="fa fa-plus"></span> Agregar Materia
        </button>
      </div>
      </form>
      </div>
  </div>
</div>


 <!-- Modal para Editar los datos de Materia-->



<!-- Modal -->
<div class="modal fade" id="editarMateria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Materia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST" id="formEditarM">
      <div class="modal-body">

      <label for="">ID</label>
<input type="number" class="form-control" id="idm" readonly="readonly"/>
        
      <label>Nombre Materia</label>
<input type="text" id="nmu" placeholder="Nombre de la materia" class="form-control">

        
      <label>Grupo</label>
    <select class="form-control" id="grupu">
    <?= $this->grupos ?>  
    </select>
   


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">
        <span class="fa fa-plus"></span> Agregar Materia
        </button>
      </div>
      </form>
      </div>
  </div>
</div>



