<div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                              
                                


                                <div class="card">
                                    <div class="card-header">
                                        <center>
                                        <strong>Registro y listado De Materias</strong>
                                    </center>

                                          
                        
                    
                        <button class="btn btn-info float-right" data-toggle="modal" data-target="#exampleModal">
                        <span class="fa fa-plus"></span>
                Agregar nuevo 
				
			</button>


                                    </div>
                                    <div class="card-body card-block">

                                    <form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Nombre de la Materia</label>
      <input type="text" class="form-control" id="inputEmail4" placeholder="Nombre de la materia">
    </div>
    <div class="form-group col-md-6">

    <label for="grupo">Grupo</label>
    <select class="form-control" id="grupo">
    <option value="0">Seleccione Grupo </option>
    <option value="1">1</option>
    <option value="2">2</option>  
    </select>




    </div>
  </div>

 








 
</form>


                                    
                                    </div>


                                    




                                    <div class="card-footer">
                                        <center>
                                        <button type="submit" class="btn btn-primary btn-sm">
                                           Registrar Materia
                                        </button>
                                    </center>
                                    </div>
                                </div>










                            </div>
                            
                        </div>

                        </div>




 <!-- Modal para insertar los datos-->



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Profesores</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        
        
      <label>Nombre de Materia</label>
    <input type="text" id="pn" name="" placeholder="Nombre de Materia" class="form-control">

    <label for="grupo">Grupo</label>
    <select class="form-control" id="grupo">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>                          
                                                                                        
               





      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="guardarnuevo">
        <span class="fa fa-plus"></span> Agregar
        </button>
      </div>
    </div>
  </div>
</div>

